name: continuous-integration-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 123456789
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5 

    steps:
    - uses: actions/checkout@v4

    - name: set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install golang-migrate CLI
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz 
        sudo mv migrate /usr/local/bin/
        which migrate

    - name: run migration
      run: make migrateup

    - name: go testing
      run: make test

